repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace

  # Github actions
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.1
    hooks:
      - id: actionlint
        name: Check Github Actions

  - repo: local
    hooks:

      # Generate CLI docs
      - id: generate-cli-docs
        name: Generate CLI Documentation
        entry: poetry run typer dreadnode_cli/__main__.py utils docs --name dreadnode --output CLI.md --title "CLI Commands"
        language: system
        pass_filenames: false
        files: ^dreadnode_cli/.*\.py$
        always_run: true
